# vim:ft=ansible:
- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: pip self-update
  pip:
    name: pip
    state: latest
    executable: /usr/local/bin/pip3

- name: Install prerequisites (python packages)
  pip:
    name: ['docker', 'PyYAML', 'docker-compose']
    executable: /usr/local/bin/pip3

- name: Ensures /home/dvzo/app dir exists
  file: path=/home/dvzo/app state=directory

- name: Add docker-compose.yml
  template:
    src: "{{item}}.j2"
    dest: "/home/dvzo/app/{{ item }}"
  with_items:
    - docker-compose.yml

- name: Tear down existing dvzo services
  community.docker.docker_compose:
    project_src: /home/dvzo/app
    state: absent
    remove_images: all
    remove_volumes: no
  ignore_errors: yes

- name: Create and start dvzo services
  community.docker.docker_compose:
    project_src: /home/dvzo/app
  register: output

- name: Check debug log of dvzo services
  ansible.builtin.debug:
    var: output

- name: Migrate database
  shell:
    cmd: "/usr/local/bin/docker-compose exec dvzo_container .venv/bin/python manage.py migrate"
    chdir: /home/dvzo/app
