# vim:ft=ansible:
- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: pip self-update
  pip:
    name: pip
    state: latest

- name: Install prerequisites (python packages)
  pip:
    name: ['docker', 'PyYAML', 'docker-compose']

- name: Ensures /root/dvzo dir exists
  file: path=/root/dvzo state=directory

- name: Add docker-compose.yml
  template:
    src: "{{item}}.j2"
    dest: "/root/dvzo/{{ item }}"
  with_items:
    - docker-compose.yml

- name: Tear down existing dvzo services
  community.docker.docker_compose:
    project_src: /root/dvzo
    state: absent
    remove_images: all
    remove_volumes: no

- name: Create and start dvzo services
  community.docker.docker_compose:
    project_src: /root/dvzo
  register: output

- name: Check debug log of dvzo services
  ansible.builtin.debug:
    var: output
