[tool.black]
line_length = 120
exclude = '(\.eggs|\.git|\.venv|venv|build|dist|migrations)'

[tool.flake8]
max-complexity = 10
max-line-length = 120
extend-ignore = "E203,D203"
exclude = ".git,__pycache__,source/conf.py,old,build,dist,venv,.venv,env,.env,migrations"

[tool.isort]
line_length = 120
include_trailing_comma = true
force_single_line = true
skip = ".git,__pycache__,source/conf.py,old,build,dist,venv,.venv,env,.env,migrations"
