# Generated by Django 3.1.6 on 2021-07-17 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_management', '0019_auto_20210712_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp')),
                ('label', models.CharField(max_length=200, verbose_name='shift_template.label')),
                ('description', models.TextField(blank=True, verbose_name='shift_template.description')),
                ('active', models.BooleanField(default=True, verbose_name='shift_template.active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_management.personnelcategory')),
                ('create_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shifttemplates', to=settings.AUTH_USER_MODEL)),
                ('update_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_shifttemplates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shift_template.singular',
                'verbose_name_plural': 'shift_template.plural',
            },
        ),
    ]
