from train_management.views.dashboard import *
from train_management.views.dayplanning import *
from train_management.views.dvzofunction import *
from train_management.views.pdf import *
from train_management.views.personnel import *
from train_management.views.phonenumber import *
from train_management.views.station import *
from train_management.views.traincomposition import *
from train_management.views.traintimetable import *
from train_management.views.traintimetabletemplate import *
from train_management.views.vehicle import *
