from train_management.views.availability import *  # noqa
from train_management.views.calendar import *  # noqa
from train_management.views.dashboard import *  # noqa
from train_management.views.dayplanning import *  # noqa
from train_management.views.dayplanning_text import *  # noqa
from train_management.views.dvzofunction import *  # noqa
from train_management.views.pdf import *  # noqa
from train_management.views.personnel import *  # noqa
from train_management.views.phonenumber import *  # noqa
from train_management.views.reservation import *  # noqa
from train_management.views.reservation_calendar import *  # noqa
from train_management.views.station import *  # noqa
from train_management.views.traincomposition import *  # noqa
from train_management.views.traintimetable import *  # noqa
from train_management.views.traintimetabletemplate import *  # noqa
from train_management.views.vehicle import *  # noqa
