from train_management.forms.dayplanning import *
from train_management.forms.dvzofunction import *
from train_management.forms.personnel import *
from train_management.forms.phonenumber import *
from train_management.forms.station import *
from train_management.forms.train import *
from train_management.forms.traintimetable import *
from train_management.forms.traintimetabletemplate import *
from train_management.forms.vehicle import *
