from train_management.models.personnel import *  # noqa
from train_management.models.dvzofunction import *  # noqa
from train_management.models.functionpersons import *  # noqa
from train_management.models.vehicle import *  # noqa
from train_management.models.dayplanning import *  # noqa
from train_management.models.train import *  # noqa
from train_management.models.station import *  # noqa
from train_management.models.traintimetabletemplate import *  # noqa
from train_management.models.traintimetable import *  # noqa
from train_management.models.mileage import *  # noqa
from train_management.models.phonenumber import *  # noqa
