from train_management.models.personnel import *
from train_management.models.dvzofunction import *
from train_management.models.functionpersons import *
from train_management.models.vehicle import *
from train_management.models.dayplanning import *
from train_management.models.train import *
from train_management.models.station import *
from train_management.models.traintimetabletemplate import *
from train_management.models.traintimetable import *
from train_management.models.mileage import *
from train_management.models.phonenumber import *
