# Generated by Django 3.1.6 on 2021-02-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarriageHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarriageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarriageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SteamHeating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('historic_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uic', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('gross_weight', models.FloatField()),
                ('traction_25', models.IntegerField()),
                ('traction_30', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('last_revision', models.DateField()),
                ('next_revision', models.DateField()),
                ('max_speed', models.IntegerField()),
                ('length', models.FloatField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('carriage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagetype')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagehome')),
                ('power_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.powerunit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagestatus')),
                ('steam_heating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.steamheating')),
            ],
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('historic_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uic', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('gross_weight', models.FloatField()),
                ('seats', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('last_revision', models.DateField()),
                ('next_revision', models.DateField()),
                ('axles_distance', models.FloatField()),
                ('length', models.FloatField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('carriage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagetype')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagehome')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carriagestatus')),
            ],
        ),
    ]
