# Generated by Django 3.1.6 on 2021-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='lup',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='axles_distance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='gross_weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='historic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='last_revision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='next_revision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='seats',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='uic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='engine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='gross_weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='historic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='engine',
            name='last_revision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='engine',
            name='max_speed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='next_revision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='traction_25',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='traction_30',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='uic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
