# Generated by Django 3.1.6 on 2021-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
