# Generated by Django 3.1.6 on 2021-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210206_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='axles_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='last_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='next_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
