# Generated by Django 3.1.6 on 2021-05-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0003_auto_20210513_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanningText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='dayplanning_text.label')),
                ('text', models.TextField(verbose_name='dayplanning_text.text')),
                ('sorting', models.IntegerField(blank=True, null=True, verbose_name='dayplanning_text.sorting')),
                ('dayplanning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_management.dayplanning')),
            ],
            options={
                'verbose_name': 'dayplanning_text.singular',
                'verbose_name_plural': 'dayplanning_text.plural',
            },
        ),
    ]
