# Generated by Django 3.1.6 on 2021-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0004_dayplanningtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='train.frequency'),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='train_timetable.frequency'),
        ),
    ]
