# Generated by Django 3.1.6 on 2021-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0005_auto_20210519_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='axles_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='vehicle.axles_distance'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='vehicle.length'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='vehicle.manufacturer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='vehicle.maximum_speed'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power_unit',
            field=models.CharField(choices=[('steam', 'vehicle.power_unit.steam'), ('diesel', 'vehicle.power_unit.diesel'), ('electric', 'vehicle.power_unit.electric'), ('dieselelectric', 'vehicle.power_unit.dieselelectric')], max_length=80, verbose_name='vehicle.power_unit'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='traction_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='vehicle.traction_25'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='traction_30',
            field=models.IntegerField(blank=True, null=True, verbose_name='vehicle.traction_30'),
        ),
    ]
