# Generated by Django 3.1.6 on 2021-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0005_auto_20210519_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='copy_recipient.label')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='copy_recipient.email')),
            ],
            options={
                'verbose_name': 'copy_recipient.singular',
                'verbose_name_plural': 'copy_recipient.plural',
            },
        ),
    ]
