# Generated by Django 3.1.6 on 2021-05-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0006_auto_20210530_1011'),
        ('train_management', '0006_copyrecipient'),
    ]

    operations = [
    ]
