# Generated by Django 3.1.6 on 2021-06-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train_management', '0007_merge_20210530_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='availability',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_availabilitys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='availability',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_availabilitys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copyrecipient',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='copyrecipient',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_copyrecipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copyrecipient',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='copyrecipient',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_copyrecipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplanning',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='dayplanning',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dayplannings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplanning',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='dayplanning',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_dayplannings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplanningtext',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='dayplanningtext',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dayplanningtexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplanningtext',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='dayplanningtext',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_dayplanningtexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dvzofunction',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='dvzofunction',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dvzofunctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dvzofunction',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='dvzofunction',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_dvzofunctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mileage',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_mileages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mileage',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_mileages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_personnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_personnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_phonenumbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_phonenumbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='route',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='route',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='station',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='station',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='train',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='train',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='train',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='train',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_trains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainconfiguration',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='trainconfiguration',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trainconfigurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainconfiguration',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='trainconfiguration',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_trainconfigurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_traintimetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_traintimetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_traintimetabletemplates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_traintimetabletemplates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
