# Generated by Django 3.1.6 on 2021-06-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train_management', '0007_merge_20210530_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='station',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='station',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
