# Generated by Django 3.1.6 on 2021-05-30 20:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0007_merge_20210530_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplanningtext',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='dayplanning_text.text'),
        ),
    ]
