# Generated by Django 3.1.6 on 2021-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0008_auto_20210603_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='carriage_type',
            field=models.CharField(blank=True, choices=[('seat', 'vehicle.carriage_type.seat'), ('gastro', 'vehicle.carriage_type.gastro'), ('luggage', 'vehicle.carriage_type.luggage'), ('cargo', 'vehicle.carriage_type.cargo'), ('amor', 'vehicle.carriage_type.amor')], max_length=80, verbose_name='vehiclecarriage_type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'vehicle.status.available'), ('servicing', 'vehicle.status.servicing'), ('ask', 'vehicle.status.ask'), ('locked', 'vehicle.status.locked'), ('not_in_service', 'vehicle.status.not_in_service')], default='available', max_length=80, verbose_name='vehicle.status'),
        ),
    ]
