# Generated by Django 3.1.6 on 2021-06-09 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train_management', '0010_auto_20210605_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp')),
                ('label', models.CharField(max_length=200, verbose_name='personnel_category.label')),
                ('type', models.CharField(choices=[('engine', 'personnel_category.type.engine'), ('train', 'personnel_category.type.train'), ('gastro', 'personnel_category.type.gastro'), ('station', 'personnel_category.type.station'), ('other', 'personnel_category.type.other')], max_length=80, verbose_name='personnel_category.type')),
                ('create_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_personnelcategorys', to=settings.AUTH_USER_MODEL)),
                ('update_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_personnelcategorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personnel_category.singular',
                'verbose_name_plural': 'personnel_category.plural',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='category',
            field=models.ManyToManyField(to='train_management.PersonnelCategory'),
        ),
    ]
