# Generated by Django 3.1.6 on 2021-06-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0012_auto_20210612_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='date_of_birth',
        ),
    ]
