# Generated by Django 3.1.6 on 2021-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0014_auto_20210616_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanning',
            name='carriage_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='carriage_planning_status'),
        ),
        migrations.AddField(
            model_name='dayplanning',
            name='engine_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='engine_planning_status'),
        ),
    ]
