# Generated by Django 3.1.6 on 2021-06-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0015_auto_20210622_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionpersons',
            name='dvzo_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_management.dvzofunction'),
        ),
        migrations.AlterField(
            model_name='functionpersons',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_management.personnel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='train_timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_management.traintimetable'),
        ),
        migrations.AlterField(
            model_name='traintimetable',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='train_management.train'),
        ),
    ]
