# Generated by Django 3.1.6 on 2021-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0015_auto_20210622_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='reservation_external',
            field=models.CharField(choices=[('not_possible', 'train_timetable.reservation_possible.not_possible'), ('possible', 'train_timetable.reservation_possible.possible')], default='not_possible', max_length=80, verbose_name='train_timetable.reservation_external'),
        ),
        migrations.AddField(
            model_name='traintimetabletemplate',
            name='reservation_internal',
            field=models.CharField(choices=[('not_possible', 'train_timetable.reservation_possible.not_possible'), ('possible', 'train_timetable.reservation_possible.possible')], default='not_possible', max_length=80, verbose_name='train_timetable.reservation_internal'),
        ),
        migrations.AlterField(
            model_name='dayplanning',
            name='carriage_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='dayplanning.carriage_planning_status'),
        ),
        migrations.AlterField(
            model_name='dayplanning',
            name='engine_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='dayplanning.engine_planning_status'),
        ),
    ]
