# Generated by Django 3.1.6 on 2021-07-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0016_auto_20210624_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvzofunction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_management.personnelcategory'),
        ),
        migrations.AlterField(
            model_name='dayplanning',
            name='carriage_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='dayplanning.carriage_planning_status'),
        ),
        migrations.AlterField(
            model_name='dayplanning',
            name='engine_planning_status',
            field=models.CharField(choices=[('open', 'dayplanning.vehicle_planning_status.open'), ('asked', 'dayplanning.vehicle_planning_status.asked'), ('ok', 'dayplanning.vehicle_planning_status.ok')], default='open', max_length=80, verbose_name='dayplanning.engine_planning_status'),
        ),
    ]
