# Generated by Django 3.1.6 on 2021-07-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_management', '0017_auto_20210707_1048'),
        ('train_management', '0017_auto_20210711_1610'),
    ]

    operations = [
    ]
