# Generated by Django 3.1.6 on 2021-06-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='article',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelet',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='articlelet',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articlelets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelet',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='articlelet',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_articlelets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerent',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='articlerent',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articlerents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerent',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='articlerent',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_articlerents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rent',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='rent',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rent',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='rent',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_rents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renter',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='renter',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_renters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renter',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_timestamp'),
        ),
        migrations.AddField(
            model_name='renter',
            name='update_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_renters', to=settings.AUTH_USER_MODEL),
        ),
    ]
