# Generated by Django 3.1.6 on 2021-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0002_auto_20210607_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='rent.total'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='rent.total_per_month'),
        ),
    ]
