# Generated by Django 3.1.6 on 2021-06-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0003_auto_20210607_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='rent.duration'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end',
            field=models.DateField(verbose_name='rent.end'),
        ),
    ]
