# Generated by Django 3.1.6 on 2021-06-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0005_articlerent_total_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerent',
            name='total_per_month',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='article_rent.total_per_month'),
        ),
    ]
