# Generated by Django 3.1.6 on 2021-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0006_auto_20210608_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerent',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='article_rent.amount'),
        ),
    ]
