# Generated by Django 3.1.6 on 2021-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0007_auto_20210608_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='let',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='let.end'),
        ),
    ]
