# Generated by Django 3.1.6 on 2021-06-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='training.training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='description',
            field=models.TextField(blank=True, verbose_name='module.description'),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='label',
            field=models.CharField(max_length=200, verbose_name='module.label'),
        ),
    ]
